name: Lint Dockerfile

on: pull_request

jobs:
  dockerfile-lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: lint
      uses: luke142367/Docker-Lint-Action@v1.1.1
      with:
        target: Dockerfile
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
